package com.hardwareai.support.knowledge;
import com.hardwareai.support.common.CurrentUser; import com.hardwareai.support.product.ProductRepository; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
/** Knowledge source upload, review and publish endpoints. */
@RestController @RequestMapping("/api") public class KnowledgeController {private final KnowledgeDocumentRepository documents;private final KnowledgeRevisionRepository revisions;private final ProcessingJobRepository jobs;private final ProductRepository products;private final ObjectStorage storage;private final CurrentUser current; KnowledgeController(KnowledgeDocumentRepository d,KnowledgeRevisionRepository r,ProcessingJobRepository j,ProductRepository p,ObjectStorage s,CurrentUser c){documents=d;revisions=r;jobs=j;products=p;storage=s;current=c;}
 @GetMapping("/documents") public List<DocumentView> list(){return documents.findAllByTenantIdOrderByCreatedAtDesc(current.tenantId()).stream().map(DocumentView::of).toList();}
 @PostMapping(value="/documents",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasRole('ADMIN')") public DocumentView upload(@RequestPart @NotBlank String title,@RequestPart @NotBlank String locale,@RequestPart UUID productModelId,@RequestPart @NotBlank String region,@RequestPart MultipartFile file){if(file.isEmpty()||file.getSize()>20*1024*1024)throw new IllegalArgumentException("A file up to 20 MiB is required");if(!Set.of("application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","image/png","image/jpeg").contains(file.getContentType()))throw new IllegalArgumentException("Only PDF, DOCX, PNG and JPEG are supported");products.findByIdAndTenantId(productModelId,current.tenantId()).orElseThrow(()->new IllegalArgumentException("Product not found"));String key=current.tenantId()+"/documents/"+UUID.randomUUID();storage.put(key,file);var doc=documents.save(new KnowledgeDocument(current.tenantId(),title,locale,key,file.getContentType(),current.userId()));var revision=revisions.save(new KnowledgeRevision(doc.id(),productModelId,region));jobs.save(new ProcessingJob(revision.id(),ProcessingJob.Type.PARSE));return DocumentView.of(doc);}
 @PostMapping("/knowledge-revisions/{id}/submit") @PreAuthorize("hasAnyRole('ADMIN','KNOWLEDGE_REVIEWER')") public void submit(@PathVariable UUID id){var r=revisions.findById(id).orElseThrow(()->new IllegalArgumentException("Revision not found"));r.submit();revisions.save(r);}
 @PostMapping("/knowledge-revisions/{id}/publish") @PreAuthorize("hasAnyRole('ADMIN','KNOWLEDGE_REVIEWER')") public void publish(@PathVariable UUID id){var r=revisions.findById(id).orElseThrow(()->new IllegalArgumentException("Revision not found"));r.publish(current.userId());revisions.save(r);jobs.save(new ProcessingJob(r.id(),ProcessingJob.Type.INDEX));}
 record DocumentView(UUID id,String title,String locale,String status){static DocumentView of(KnowledgeDocument d){return new DocumentView(d.id(),d.title(),d.locale(),d.status().name());}}
}
